apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  labels:
    app: miniblog
type: Opaque
stringData:
  DB_PASSWORD: "root"
  JWT_SECRET: "supersecretkey"
  JWT_EXPIRES_IN: "1h"
  BCRYPT_SALT_ROUNDS: "10"
